### PR TITLE
Added Spring context awareness support

### PR DESCRIPTION
**Pull request by rizjoj**
Hi @Clayton7510 - PR is more for discussion than merging/approval. Let me know what you think.

### CODE REVIEW

**Comment by rizjoj** [comment]
Usage: Everything else stays the same (follow documentation sections 5.3 and 5.4), except annotate just the rules you want spring aware with `@Component` (you don't have to annotate all rules), and within the rules now `@Autowire` injection, etc. works. No need to introduce your beans in the factMap and fetch them via `@Given`.

**Comment by Clayton7510** [comment]
I do like the idea of being able to support @Autowire inside of POJO beans. This has been discussed a bit. The only issue I have is that I wouldn't want it bound to all RuleBookRunner's, like what would happen if you add context awareness to AbstractRuleBookRunner. 

Instead, perhaps a different RuleBookRunner in rulebook-spring could be added since it would be specific to Spring. This also has the benefit of not tying rulebook-core to spring dependencies, which I think is important. Some people do use rulebook without spring (e.g. JavaEE and Guice).

Aside from those couple of items, I think where you are going is great!

**Comment by Clayton7510** [comment]
Oh, and as far as ```@RuleBean``` goes... originally RuleBook was not thread safe and RuleBookRunner wired up individual rules. So, ```@RuleBean``` made POJO rules Spring ```@Component```'s and it also made them prototype scoped. Now, RuleBean can still be used. But it might better just to deprecate it in favor of just using @Component.

**Comment by rizjoj** [comment]
Superceeded by PR #134

**Comment by lanegoolsby** [comment]
I was able to get @Autowire to work by adding both @Rule and @RuleBean annotations to my POJO classes. I couldn't get Autowire to work with POJO classes in a Spring Boot app until I did that. I may be oversimplfying (or setting myself up for disaster) but it seems the reason @Rule POJO's don't work with Spring injection is because the reflective call to find the POJO objects only searches for objects that implement @Rule. This all might be solvable by just making @RuleBean implement @Rule.

**Comment by Clayton7510** [comment]
@lanegoolsby, @RuleBean does extend @Rule. The reason why you needed @Rule and @RuleBean annotations to make @Autowire work was because @RuleBean also extends @Component, which is what Spring needs to @Autowire inject beans. The reason why it doesn’t just work with @RuleBean is partly because of how annotations are resolved via Reflection and partly because @RuleBean hasn’t really been touched in a while.

The plan is to fix it so that you would only need @RuleBean for Spring aware POJO rules.

Thanks for the comment. Look for this to be updated within the next week.

**Pull request closed without merging**
